In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt  
%matplotlib inline
import math
import warnings 
warnings.filterwarnings('ignore')

covid_data = pd.read_csv("C:\\Users\JOSEPHINE\Downloads\covid.csv")
covid_data.head(10)

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   
5                  1      1          1            0            0       0   
6                  1      1          1            0            0       0   
7                  1      1          1            0            1       1   
8                  1      1          1            0            1       0   
9                  1      1          1            0            0       1   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue  \
0                     0         0              0         1  ...        1   
1                     1         1              0         0  ...        1   
2                     1         1              0         1  ...        1   
3                     0         0              1         1  ...        0   
4                     1         1              1         1  ...        0   
5                     0         0              1         0  ...        0   
6                     1         0              1         1  ...        1   
7                     0         0              0         1  ...        0   
8                     1         0              0         1  ...        1   
9                     0         0              0         1  ...        1   

   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                  1              0                           1   
1                  0              0                           0   
2                  1              1                           0   
3                  0              1                           0   
4                  1              0                           1   
5                  0              0                           0   
6                  1              0                           0   
7                  1              1                           0   
8                  0              1                           1   
9                  0              0                           0   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   
5                         0                              0   
6                         1                              1   
7                         0                              1   
8                         1                              0   
9                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   
5                                        0              0   
6                                        1              0   
7                                        0              0   
8                                        0              0   
9                                        0              0   

   Sanitization from Market  COVID-19  
0                         0         1  
1                         0         1  
2                         0         1  
3                         0         1  
4                         0         

In [8]:
print("# of patients in original data: "+str(len(covid_data.index)))

# of patients in original data: 5434


In [9]:
covid_data.shape

(5434, 21)

In [10]:
covid_data.isnull()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                 False  False      False        False        False   False   
1                 False  False      False        False        False   False   
2                 False  False      False        False        False   False   
3                 False  False      False        False        False   False   
4                 False  False      False        False        False   False   
...                 ...    ...        ...          ...          ...     ...   
5429              False  False      False        False        False   False   
5430              False  False      False        False        False   False   
5431              False  False      False        False        False   False   
5432              False  False      False        False        False   False   
5433              False  False      False        False        False   False   

      Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue  \
0                    False     False          False     False  ...    False   
1                    False     False          False     False  ...    False   
2                    False     False          False     False  ...    False   
3                    False     False          False     False  ...    False   
4                    False     False          False     False  ...    False   
...                    ...       ...            ...       ...  ...      ...   
5429                 False     False          False     False  ...    False   
5430                 False     False          False     False  ...    False   
5431                 False     False          False     False  ...    False   
5432                 False     False          False     False  ...    False   
5433                 False     False          False     False  ...    False   

      Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                 False          False                       False   
1                 False          False                       False   
2                 False          False                       False   
3                 False          False                       False   
4                 False          False                       False   
...                 ...            ...                         ...   
5429              False          False                       False   
5430              False          False                       False   
5431              False          False                       False   
5432              False          False                       False   
5433              False          False                       False   

      Attended Large Gathering  Visited Public Exposed Places  \
0                        False                          False   
1                        False                          False   
2                        False                          False   
3                        False                          False   
4                        False                          False   
...                        ...                            ...   
5429                     False                          False   
5430                     False                          False   
5431                     False                          False   
5432                     False                          False   
5433                     False                          False   

      Family working in Public Exposed Places  Wearing Masks  \
0                                       False          False   
1                                       False          False   
2                                       False          False   
3                                       False          False   
4                                       False          False   
...                                       ...            ...   
5429                                  

In [11]:
 covid_data.isnull().sum()

Breathing Problem                          0
Fever                                      0
Dry Cough                                  0
Sore throat                                0
Running 0se                                0
Asthma                                     0
Chronic Lung Disease                       0
Headache                                   0
Heart Disease                              0
Diabetes                                   0
Hyper Tension                              0
Fatigue                                    0
Gastrointestinal                           0
Abroad travel                              0
Contact with COVID Patient                 0
Attended Large Gathering                   0
Visited Public Exposed Places              0
Family working in Public Exposed Places    0
Wearing Masks                              0
Sanitization from Market                   0
COVID-19                                   0
dtype: int64

## Train Dataset

In [12]:
X= covid_data.drop("COVID-19", axis=1)
y= covid_data["COVID-19"]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
SSX=scaler.transform(X)

## Train Test Split

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(SSX, y, test_size=0.3, random_state=1)

## Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression(solver='liblinear',multi_class='ovr')
logmodel.fit(X_train, y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [15]:
logistic_prediction= logmodel.predict(X_test)

In [16]:
from sklearn.metrics import classification_report

In [19]:
classification_report(y_test,logistic_prediction)

'              precision    recall  f1-score   support\n\n           0       0.94      0.88      0.91       326\n           1       0.97      0.99      0.98      1305\n\n    accuracy                           0.97      1631\n   macro avg       0.96      0.94      0.95      1631\nweighted avg       0.97      0.97      0.97      1631\n'

In [20]:
from sklearn.metrics import confusion_matrix

In [22]:
confusion_matrix(y_test,logistic_prediction)

array([[ 288,   38],
       [  17, 1288]], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
print("Train Accuracy of Logistic Regression",logmodel.score(X_train,y_train)*100)
print("Accuracy (Test) score of Logistic Regression", logmodel.score(X_test,y_test)*100)
print("Accuracy Score of Logistic Regression", accuracy_score(y_test,logistic_prediction)*100)

Train Accuracy of Logistic Regression 97.21272679463581
Accuracy (Test) score of Logistic Regression 96.62783568362967
Accuracy Score of Logistic Regression 96.62783568362967


In [44]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
logistic_auc = roc_auc_score(y_test, logistic_prediction)

In [45]:
print('Logistic Regression: ROC AUC=%.3f' % (logistic_auc))

Logistic Regression: ROC AUC=0.935


## K-nearest Neighbor

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [26]:
knn_prediction=knn.predict(X_test)

In [27]:
classification_report(y_test,knn_prediction)

'              precision    recall  f1-score   support\n\n           0       0.96      0.94      0.95       326\n           1       0.98      0.99      0.99      1305\n\n    accuracy                           0.98      1631\n   macro avg       0.97      0.96      0.97      1631\nweighted avg       0.98      0.98      0.98      1631\n'

In [28]:
confusion_matrix(y_test,knn_prediction)

array([[ 306,   20],
       [  12, 1293]], dtype=int64)

In [29]:
print("Train Accuracy of K-nearest Neighbor", knn.score(X_train,y_train)*100)
print("Accuracy (Test) score of K-nearest Neighbor", knn.score(X_test,y_test)*100)
print("Accuracy Score of K-nearest Neighbor", accuracy_score(y_test,knn_prediction)*100)

Train Accuracy of K-nearest Neighbor 97.97528267157507
Accuracy (Test) score of K-nearest Neighbor 98.03801348865726
Accuracy Score of K-nearest Neighbor 98.03801348865726


In [49]:
knn_auc = roc_auc_score(y_test, knn_prediction)
print('KNN: ROC AUC=%.3f' % (knn_auc))

KNN: ROC AUC=0.965


## Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(criterion='entropy')
rf.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy')

In [31]:
rf_prediction= rf.predict(X_test)

In [32]:
classification_report(y_test,rf_prediction)

'              precision    recall  f1-score   support\n\n           0       0.97      0.96      0.96       326\n           1       0.99      0.99      0.99      1305\n\n    accuracy                           0.98      1631\n   macro avg       0.98      0.97      0.98      1631\nweighted avg       0.98      0.98      0.98      1631\n'

In [33]:
confusion_matrix(y_test,rf_prediction)

array([[ 312,   14],
       [  11, 1294]], dtype=int64)

In [34]:
print("Train Accuracy of Random Forest", rf.score(X_train,y_train)*100)
print("Accuracy (Test) score of Random Forest", rf.score(X_test,y_test)*100)
print("Accuracy Score of Random Forest", accuracy_score(y_test,rf_prediction)*100)

Train Accuracy of Random Forest 98.18564291348935
Accuracy (Test) score of Random Forest 98.46719803801349
Accuracy Score of Random Forest 98.46719803801349


In [50]:
rf_auc = roc_auc_score(y_test, rf_prediction)
print('Random Forest: ROC AUC=%.3f' % (rf_auc))

Random Forest: ROC AUC=0.974


## Support Vector Machine

In [35]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,y_train)

SVC()

In [36]:
svm_prediction= svm.predict(X_test)

In [38]:
classification_report(y_test,svm_prediction)

'              precision    recall  f1-score   support\n\n           0       0.97      0.94      0.95       326\n           1       0.99      0.99      0.99      1305\n\n    accuracy                           0.98      1631\n   macro avg       0.98      0.97      0.97      1631\nweighted avg       0.98      0.98      0.98      1631\n'

In [40]:
confusion_matrix(y_test,svm_prediction)

array([[ 307,   19],
       [  10, 1295]], dtype=int64)

In [41]:
print("Train Accuracy of Decision Tree", svm.score(X_train,y_train)*100)
print("Accuracy (Test) score of Decision Tree", svm.score(X_test,y_test)*100)
print("Accuracy Score of Decision Tree", accuracy_score(y_test,svm_prediction)*100)

Train Accuracy of Decision Tree 98.15934788325006
Accuracy (Test) score of Decision Tree 98.22194972409565
Accuracy Score of Decision Tree 98.22194972409565


In [51]:
svm_auc = roc_auc_score(y_test, svm_prediction)
print('SVM: ROC AUC=%.3f' % (svm_auc))

SVM: ROC AUC=0.967
